### ISSUE TITLE
Tenants should not be able to create multiple products with the same name

### ISSUE THREAD

**Issue by mobileoverlord** [nerves-hub/nerves_hub_web#145]
Product names should be unique under tenants.

**Comment by jlmcgehee21** [comment]
@mobileoverlord Did I get something wrong in this migration? https://github.com/nerves-hub/nerves_hub_web/blob/4f04f28418b6490d52eaa7cbcc54273eb2ea6c2b/apps/nerves_hub_core/priv/repo/migrations/20180710140434_create_products.exs#L28 . Looking through the ecto docs now, but this was my attempt at having unique product names within the scope of a tenant.

**Comment by jlmcgehee21** [comment]
@mobileoverlord `create/1` was not called on the `unique_index` in this migration, as well as a few others within the project.  Kudos to @danielspofford for helping me find that.  I'll try to fix all the other places it's messed up as well.  I guess they snuck through the cracks because there weren't any tests enforcing uniqueness.

**Comment by mobileoverlord** [comment]
<img width="420" alt="screen shot 2018-07-30 at 17 13 04" src="https://user-images.githubusercontent.com/1391351/43423954-dacbc90a-941b-11e8-9945-06e05090cd70.png">
Accepted in production
