### ISSUE TITLE
Elixir 1.14 Project won't compile 

### ISSUE THREAD

**Issue by jbnoblot** [nerves-hub/nerves_hub_web#1610]
**Describe the bug**
When I `mix compile` i received an error 

> == Compilation error in file lib/nerves_hub/devices.ex ==
> ** (CompileError) lib/nerves_hub/devices.ex:1364: undefined function get_in/1
> 

**To Reproduce**
1. install Elixir < 1.17.0
2. clone project
3. mix deps.get && mix compile

**Expected behavior**
I am very a big noob in elixir worlds but in mix.exs, in project section I see elixir 1.11

**Desktop (please complete the following information):**
 - OS: Linux (Lubuntu 24.04)
 - Elixir version 1.14

**Additional context**
https://github.com/nerves-hub/nerves_hub_web/blob/50321d6e71a565365f6755d7e944de8195c3f6e6/lib/nerves_hub/devices.ex#L1364
We use get_in\1 but it's introduce in Elixir 1.17
maybe Up elixir version in mix.exs or use `get_in\2`

**Comment by fhunleth** [comment]
I believe we really only use the Elixir version in the [`.tool-versions`](https://github.com/nerves-hub/nerves_hub_web/blob/main/.tool-versions). @joshk, @jjcarstens, or @lawik - Do any of you know different? I think we should update the `mix.exs` to require it. It feels even more important to check the Erlang version since there are known issues that affect NervesHub with some old versions.

@jbnoblot Could you update the version of Elixir that you're using? You'll need to update your Erlang version too.

**Comment by lawik** [comment]
Yeah, I would say shoving the mix version forward makes a bunch of sense.

**Comment by lawik** [comment]
It would be atypical to run this on some other Elixir version than what the .tool-versions intends. Evidently this happens :) but maybe we don't trick people into it.

**Comment by jbnoblot** [comment]
Hello, I am a beginner in the world of elixir. Indeed, I am not familiar with all the tools and I took the wrong way on how to compile and use the project. Sorry

@fhunleth Yes i can up Elixir/Erlang version

**Comment by lawik** [comment]
Oh absolutely no need to apologize. This is clearly a blind spot on our end and you helped us realize we have a gap to close.

Very much appreciate the report :)

let us know if you have any more issues with NervesHub. Bugs fit here (like this one) and ElixirForum is good for general help ✨

**Comment by lawik** [comment]
@jbnoblot want to do a PR bumping the version mix.exs to match the one in .tool-versions? Get yourself a contribution on the record? Otherwise I can do it.
