### ISSUE TITLE
Ensure presence messages are not sent to firmware topic

### ISSUE THREAD

**Issue by mobileoverlord** [nerves-hub/nerves_hub_web#197]
Want to double check and add a test to ensure that presence messages are not sent to all devices in the same firmware topic. Its just unnecessary noise.

**Comment by mobileoverlord** [comment]
I think this was addressed in a recent change, right @danielspofford

**Comment by danielspofford** [comment]
Intercept here: https://github.com/nerves-hub/nerves_hub_web/blob/master/apps/nerves_hub_device/lib/nerves_hub_device_web/channels/device_channel.ex#L14

Throwaway handle out here: https://github.com/nerves-hub/nerves_hub_web/blob/master/apps/nerves_hub_device/lib/nerves_hub_device_web/channels/device_channel.ex#L56

Refute receive presence diff here: https://github.com/nerves-hub/nerves_hub_web/blob/master/apps/nerves_hub_device/test/nerves_hub_device_web/websocket_test.exs#L119

But a more focused test that actually indicated its intent `test "does not receive presence messages" do` would probably be better since someone could remove this line thinking it was extraneous at some point.

Also, it is only refuting that `presence_diff` was received, it should also ensure `presence_state` is not received.
