### ISSUE TITLE
What does it mean to "disable" a device?

### ISSUE THREAD

**Issue by jlmcgehee21** [nerves-hub/nerves_hub_web#248]
There is a non-functional button in the web UI for "disabling" a device.

If this is a feature we want to have, we need to define the state of a "disabled" device and the mechanics of "disabling" a device.

**Comment by fhunleth** [comment]
The need for a disable button on a device is that there are times where you want to prevent devices from being managed temporarily. One example is to disable updates to a misbehaving device so that it can be debugged or it can "cool" down. Deleting the device and then re-adding it seems error-prone. Having said that, I can't think of a reason why "disable" is a near term need, so I completely agree with your PR to remove the button for now. I also don't mind waiting a bit to refine the idea of disabling a device.

**Comment by jlmcgehee21** [comment]
Awesome.  Those reasons for disabling a device seem totally valid.  The thing that we need to clarify is the mechanism by which we will consider the device to be disabled.

Is it a boolean field on the device in the database? If so, how does the client behave in that instance?

**Comment by fhunleth** [comment]
I've always assumed that it was a boolean field on the device in the database. I don't think there's a reason for it to be anything more.

As for the client, the main thing is that the client doesn't get firmware updates. After that, I think there are two possible options: 1. let the client connect like normal and be totally oblivious to being disabled (they just think that there's no update), or 2. revoke the client's cert so that the SSL layer stops them. I think that option 1 is all that matters for now. I think that client cert revocation can be it's own issue.

**Comment by fhunleth** [comment]
Added device cert revocation as #250.

**Comment by jlmcgehee21** [comment]
@fhunleth -- To me, disable implies the ability to "re-enable" _without_ pushing new firmware. 

If this is the case, wouldn't cert revocation would be reserved for _deleted_ devices?

**Comment by mobileoverlord** [comment]
This can be handled by quarantining a device as well as removing its cert.
