### ISSUE TITLE
Internal server error when deleting a firmware signing key that's in use

### ISSUE THREAD

**Issue by fhunleth** [nerves-hub/nerves_hub_web#291]
**Describe the bug**
Log into nerves-hub.org. Find a firmware signing key that was used to sign a firmware image that's on the server. Try to delete it. You'll get an internal server error.

**Expected behavior**
I'd expect an error message that says that the key is in use and can't be deleted.

**Comment by mobileoverlord** [comment]
I think part of the problem is that we need to validate device association constraints. 

https://github.com/nerves-hub/nerves_hub_web/blob/master/apps/nerves_hub_core/lib/nerves_hub_core/firmwares/firmware.ex#L78-L82

We have one for deployments, so I would suspect that you would be given an error if you try to remove one that is associated to a deployment but not any devices.
