### ISSUE TITLE
Matching deployments are not enumerated

### ISSUE THREAD

**Issue by ConnorRigby** [nerves-hub/nerves_hub_web#301]
https://github.com/nerves-hub/nerves_hub_web/blob/master/apps/nerves_hub_device/lib/nerves_hub_device_web/controllers/device_controller.ex#L19

https://github.com/nerves-hub/nerves_hub_web/blob/master/apps/nerves_hub_device/lib/nerves_hub_device_web/channels/device_channel.ex#L62

This may be intended, but this only checks the first eligible deployment as far as i can tell.
If it is intended i believe a comment is in order

**Comment by jjcarstens** [comment]
In doing some other work, I noticed this behavior as well. Is there a case to want to iterate between deployments? It seems like we would only want a _single_matching deployment because we don't want to tell a device it has 2 different updates at once and have it guess which to apply.

The case I seeing for iterating is maybe a device is very behind and needs to go through a few fw versions in succession? But even then, it would just get one eligible deployment at a time and I'm not entirely sure that's a case we'd want to support?

**Comment by ConnorRigby** [comment]
I did a bad job at making links that would persist into the future, but from what i remember, when determining a valid deployment, the first item in a list of matching is chosen. But the generation of the list is non-deterministic. IE two devices with the same configuration could be served different updates.

**Comment by joshk** [comment]
I'm closing this issue for the time being as it has become stale.
