### ISSUE TITLE
Support deletion of accounts

### ISSUE THREAD

**Issue by fhunleth** [nerves-hub/nerves_hub_web#421]
Currently it's possible to create an account, but once you're done with NervesHub, there's no way to delete the account.

**Comment by chazwatkins** [comment]
Would we prefer a soft or hard delete?

Should the user's **owned** orgs, devices, firmware, deployments, etc be removed when the user is removed?

**Comment by fhunleth** [comment]
That's a good question.

I curious on others opinions, but I'd want a soft delete. I'd like to preserve data so that connections from orphaned devices could be traced to their original owners and handled specially should they become disruptive. Hard deleting orphaned firmware and deployments seems less problematic. I'd be fine with soft deleting those too with the assumption that orphaned firmware files would eventually be garbage collected.

**Comment by brianberlin** [comment]
Excuse me while i fumble around with this draft PR. I'm still getting the hang of all these relationships and constraints. I was able to get some code together for removing a basic account without org users. Once a second org is created and users are invited it looks to become a little more challenging. I've also not gotten into the soft delete part which will also take some cycles to get right.

More rambles... It looks like if we want devices to be soft deleted, we'll also need to do the same for orgs and products. I think because of the way tags work we should be able to delete everything else. In order to tackle orgs with org users, I should maybe shift focus to deleting orgs next. Should any admin be able to delete an org? 🤔

**Comment by jjcarstens** [comment]
I would assume an admin level should probably be able to delete an org since we're dealing with soft delete.

**Comment by ConnorRigby** [comment]
Closed via #421
