### ISSUE TITLE
Validate email addresses of users created via mix nerves_hub.user register

### ISSUE THREAD

**Issue by fhunleth** [nerves-hub/nerves_hub_web#425]
It's currently possible to create users with bad email addresses. We'd like everyone to have validated email addresses to minimally confirm identity, prevent shenanigans, and make sure that email notifications are received.

If an account's email address isn't confirmed in an hour, it's safe to remove the account. I'm open to longer durations too.

**Comment by pcmarks** [comment]
Suggested fix: 

A user account will *not* be created as a result of `mix nerves_hub.user register`

Instead, after the user enters `mix nerves_hub.user register` and the email, etc is gathered: 

-  Create and send an invitation via an API request.
- Then, print the following: 
`An invitation has been sent to this email address: #{email}. In order to create an account you must respond within ?. If you don’t see the invitation, please check your spam folder.
`

Once users have accepted the invitation and their user account has been created, they can return to the CLI and perform a `mix nerves_hub.user auth`.

The expiration duration is hardcoded in nerves_hub_web_core; it is currently set at 48 hours.

Repos/Apps that need to change:

- nerves_hub
	Change README - Different explanation of cli register task

- nerves_hub_cli
Possibly change the README to be more expicit about user registration, etc.
	Change user register task per above.
	Call NervesHubUserAPI.User.invite

- nerves_hub_user_api

	new: NervesHubUserAPI.User.invite() 
		request: GET /users/invite

- nerves_hub_web/nerves_hub_api_web

	new route: GET /users/invite -> UserController.invite
new: NervesHubAPIWeb.UserController.invite()

- nerves_hub_web/nerves_hub_web_core

	?Change invitation expiration time?

**Comment by jjcarstens** [comment]
We could go this route. That would essentially break registering a user from CLI to a local nerves hub instance (though that's not the worst I suppose). If we went this route, it would be nice to add a return or note in the README or something stating for local development, one should create an account through the web UI.

**Comment by pcmarks** [comment]
What is the purpose of the CLI other than to give someone access via a terminal window? Wouldn't that user most likely have access to a browser on their system? The NervesHub servers would be running.

A variation on the above would be to completely eliminate registration via the CLI. I don't know if that would  be inconvenient to the target users. So, registration would only be done via the UI.

**Comment by jjcarstens** [comment]
I think those are correct assumptions. The CLI seems to be geared towards those who prefer REPL than the web (and as such is more inclusive than the web).

If we eliminate registration from the CLI, I think we'd need to open it up in the web (currently disabled, even when I try to manually enter the URL)
![image](https://user-images.githubusercontent.com/11321326/57029596-78db9600-6bff-11e9-87c2-bf7165c36300.png)

So I think the appropriate route is as proposed so that we more quickly validate emails. And my concern only affects development when using the CLI with a local nerves hub instance, which _does_ allow registration through the UI. So it would be easy to alter the `nerves_hub_web` to return "use the web" if its in dev env and someone hits it via the CLI.

**Comment by pcmarks** [comment]
Interestingly, registering a new user - via the "Create Account" button cause a crash. NervesHub is trying to send an email to everyone in the organization, except there is no organization! I introduced this bug when I added email notifications to everyone in an organization. So, since we will be allowing registration via the UI, this needs to be fixed.

I'd like to fix it by adding a `register()` function to AccountController. Right now the `create()` function handles both adding a user as the result of an invitation - `POST /invite` - and registering a user - `POST /register`. 

My understanding that for this kind of fix, an issue is not required, only a PR.

**Comment by fhunleth** [comment]
Sorry - I've been busy, but to clarify, we will not be enabling signups via the web UI until we have billing in place. I'm not sure when that will be, but probably not in the next few weeks.

**Comment by pcmarks** [comment]
OK. Good to know.
The original plan (above) should still be valid, i.e., instead of registering that user, email an invitation so as to verify their email address.

**Comment by joshk** [comment]
I'm going to close this issue for the time being as so much has changed in the last 5 years.
