### ISSUE TITLE
Firmware Update API endpoint - "Urgent" field

### ISSUE THREAD

**Issue by paulstatezny** [nerves-hub/nerves_hub_web#44]

**Comment by fhunleth** [comment]
I believe this is a hint to the device for when to apply the update. Urgent means "do it now". Not urgent means "apply it when convenient". For example, it could be when the system is idle or off-hours. 

I think this requires some thought in light of all of the development that's happened since March. I'm fine with closing and then re-opening when we'd actually use it.

(Hitting close to save other's time. Please re-open if you disagree).
