### ISSUE TITLE
Web: Unable to create device with tags and defaults tags to "all"

### ISSUE THREAD

**Issue by jjcarstens** [nerves-hub/nerves_hub_web#652]
I just noticed that new devices created with the web prevents specifying tags _and_ defaults the tags to `["all"]`

I would actually consider this an anti pattern as tags are designed as a form of explicit filtering and identification. A default tag adds an implicit assertion. We also don't enforce this "all" tag when creating devices from the API.

I think we need to allow adding tags when creating the device again and remove the default "all" tag as to not encroach on user setup.

**Comment by jjcarstens** [comment]
cc/ @coryjewell @Mrjaco12 

This seems to have come in with the new UI. Is there a specific reason this behavior was changed that I am just unaware of?

**Comment by oantila** [comment]
The user feedback we got from some people was that the way deployments are done via tags is confusing and it would be nice if there was a simple way to quickly deploy firmware to all devices without having to think about tags at all.

We needed some way of grouping all devices together since a tag is required for a deployment, hence the All tag. We also wanted to simplify the new device creation flow, which is why the tags input field is hidden there. It is accessible in the device edit form though.

It's not a very elegant solution though and later we'd like to come up with something better. In the meantime, we're cool with removing the default All tag and adding the Tags field back in for the device creation form.

**Comment by fhunleth** [comment]
Since you can remove the 'all' tag, isn't that confusing? And was it added to all of the existing devices? I don't see it on any of my devices, but before someone adds tags to my deployed devices, could we discuss this? This would affects us operationally.

**Comment by oantila** [comment]
It hasn't been added to any existing devices. It only gets added to new devices created via the web UI but it can still be removed like any other tag.

**Comment by fhunleth** [comment]
Got it. I onboard with your comment about removing the default All tag and adding the Tags field back.

**Comment by jjcarstens** [comment]
I feel like a good path forward is better explanation within web of what tags/groups are.

To me, the inability to quickly group all devices is a feature - it makes it explicit and, subsequently, hard to accidentally deploy bad/false target firmware to every single device. It also forces the user to make effort on what groupings they want, all supporting the reduced risk of bad firmware deployment.

Maybe some better notes in the web on how tags and deployments are related would be helpful. And a way to bulk import many devices at once from the UI could also be useful too - the user would make the groupings in a spreadsheet, then apply all at once.
