### ISSUE TITLE
DeviceCert with no Common Name fails to verify

### ISSUE THREAD

**Issue by ConnorRigby** [nerves-hub/nerves_hub_web#702]
While debugging a different issue, we found a device in the logs spamming the server with reconnects because the cert has no common_name

**Comment by jjcarstens** [comment]
I'm assuming we want verification to still fail when CommonName in the cert does not match the device identifier, but with a better error here instead?

**Comment by fhunleth** [comment]
Yes, the problem was that the lack of the common name would turn into an exception which would fill the logs. The first desire was for it to return error rather than crash. Then, and I'm not sure if this is possible, it would be nice if the error back to the user could tell them to add a common name to their certs. It's a weird error in that the cert being presented passes authentication, but it was made without the required contents for use with NervesHub.

**Comment by jjcarstens** [comment]
This was fixed with #715
