### ISSUE TITLE
Support Just-in-Time registration

### ISSUE THREAD

**Issue by fhunleth** [nerves-hub/nerves_hub_web#71]
Since we're requiring client-side certificates, offering a JIT registration capability seems really convenient. See https://aws.amazon.com/blogs/iot/just-in-time-registration-of-device-certificates-on-aws-iot/ for how AWS handles it.

**Comment by mobileoverlord** [comment]
I've read through the procedure for AWS and it seems that we have discussed a mechanism similar to this.

In the discussed scenario, the organization runs their own instance of the `NervesHub.CA` service.

* The organization can generate a single intermediate certificate.
* The organization can run an instance of `nerves_hub_ca` in their local environment.
* `nerves_hub_ca` is configured with the generated intermediate as the locally running root ca certificate.
* Device certificates are generated locally against the trusted intermediate. 

I believe this is essentially the same as the aws offering, except, the initial certificate has to be generated based on the main `nerves_hub_ca` to the sub certificates are all part of the same chain of trust instead of uploading a top level that we would have to track on the server side ourselves. The benefit is that all our servers can run client side ssl authentication using the same ssl certificates allowing all the device traffic to come in through the same scope like `connect.nerves-hub.org`. I believe it would be more difficult if we allowed organizations to upload separate chains of trust since we would need to bind those certs to certain scopes. For example, we would likely have to start a ranch process for each client using their own root ca cert and mount it at an isolated scope, like `connect.orginization.nerves-hub.org`.

**Comment by fhunleth** [comment]
I believe the key part for JIT is that tenants don't need to register device UUIDs before the devices connect. With JIT registration, nerves-hub would see that the device has a good cert, extract the UUID and serial number from that cert, and create the device. Since you're creating an intermediate cert for each tenant, nerves-hub could see which intermediate cert was in the client chain and use that information to determine the tenant for the device.

I'm totally fine with requiring UUIDs to be registered with the server for the first releases. I think that everything you're doing now leads to us being able to support JIT in the future.

**Comment by fhunleth** [comment]
Reopening since the device record creation isn't automatic.

**Comment by jjcarstens** [comment]
implemented
