### ISSUE TITLE
Firmware update message is sent (if needed) when device joins channel.

### ISSUE THREAD

**Issue by jlmcgehee21** [nerves-hub/nerves_hub_web#79]
References: https://github.com/nerves-hub/nerves_hub/blob/master/docs/client-server.md

> Next, the server compares the running version of the firmware to the target version for that device on NervesHub. If those versions are different, then the channel queues a firmware update message to be sent as soon as the channel finishes the join process.

Depends On: #78

**Comment by jlmcgehee21** [comment]
We will need to look up devices by the `serial` added to `socket.assigns` in order to check the target version.  I'm guessing this should map somehow to `:identifier`, is there a method for this that is specified somewhere?

Still browsing the codebase to see what I can find as well.

**Comment by fhunleth** [comment]
If I understand correctly, I think that `serial` needs to be mapped directly to `:identifier` for the time being. This code was written before we wanted to deal with the issue of IDs being reused across tenants. The current plan is to assign UUIDs to devices in addition to manufacturing-assigned serial numbers. Code would work with UUIDs. Humans would see the serial numbers (for the most part). Both numbers would be embedded in the certs. Since we're hand generating certs at the moment, I think that it's ok to skip worrying about UUIDs until cert generation is available.

@mobileoverlord You agree? I know that you're getting close on cert generation, but it's still probably end next week-ish before you have something ready.

**Comment by jlmcgehee21** [comment]
☝️ gets us part of the way there, but I think this issue should stay open until we can send an _actual_ firmware image.
