### ISSUE TITLE
Server error when uploading a new CA signed by root-ca-key.pem

### ISSUE THREAD

**Issue by don** [nerves-hub/nerves_hub_web#854]
**Describe the bug**
There's a server error when uploading a new CA for an organization if the CSR is signed but root-ca-key.pem instead of device-root-ca-key.pem

ArgumentError at POST /settings/foo/certificates
expected argument to be a literal atom, literal keyword or a :Extension record, got runtime: nil
(see screenshots)

**To Reproduce**
1. Create a new certificate for your organization http://localhost:8080/settings/foo/certificates/new
2. Follow instructions on page to create key, csr, and certificate
3. Use root-ca-key.pem and root-ca.pem to sign the CSR
4. Upload CA and Cert
5. Error (See 2nd screenshot)

The server has an error reading the extension
https://github.com/nerves-hub/nerves_hub_web/blob/694a883468aa07cd6c47f577a8dc7cdf0a89bfab/apps/nerves_hub_web_core/lib/nerves_hub_web_core/certificate.ex#L20

**Expected behavior**
Expected to see the certificate uploaded

**Screenshots**
<img width="1472" alt="Screen Shot 2022-09-30 at 1 05 04 PM" src="https://user-images.githubusercontent.com/3133/193321934-d3916d1b-2eda-43f9-b3ee-19535cbe8750.png">
<img width="1678" alt="Screen Shot 2022-09-30 at 1 05 22 PM" src="https://user-images.githubusercontent.com/3133/193322042-c8275249-0f45-41a1-ae38-872373ff22c6.png">

**Additional context**
This works if I use device-root-ca-key.pem and device-root-ca.pem to sign the CSR

I think the solutions is 2 fold
1) Clarify the instructions for Step 4 and should clarify which key to use to sign the new CA
2) If the wrong CA is used, don't crash, give the user a message

I'm willing to help with a PR for this

**Comment by don** [comment]
I think this might be related to the underlying issue. I get the same error when uploading a device certificate signed by the org CA.

    % mix nerves_hub.device cert import nerves nerves.cert
    
```
# ArgumentError at POST /orgs/don/products/hello_nerves/devices/nerves/certificates

Exception:

    ** (ArgumentError) expected argument to be a literal atom, literal keyword or a :Extension record, got runtime: nil
        (elixir 1.12.2) lib/record.ex:511: Record.__keyword__/3
        (nerves_hub_web_core 0.1.0) lib/nerves_hub_web_core/certificate.ex:20: NervesHubWebCore.Certificate.get_aki/1
```

The certificate I'm uploading has X509v3 extensions
```
openssl x509 -text -in nerves.cert
....
        X509v3 extensions:
            X509v3 Basic Constraints: 
                CA:FALSE
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment
            X509v3 Extended Key Usage: 
                TLS Web Client Authentication
```

The org CA was generated based on the step 4 instructions above
The org CA does NOT have any X509v3 extensions which might be causing this error

**Comment by jjcarstens** [comment]
So I think there is a misunderstanding here of what this page is for.

First lets address that `mix nerves_hub.device cert import` is used to import a _device_ certificate to the device database record in NervesHub. It is not meant for use with signer CA certificates for the organization. So the error listed is expected

Second, this screen is for adding a custom, self managed signer CA certificate to your organization. It requires that you create the signer certificate, typically via the `mix nerves_key.signer create` task, and then using these commands/instructions to prove that you have ownership of that signer certificate and private key by creating a "verification certificate" with the expected token that NH can read and verify on upload. What you are attempting using `root-ca-key.pem` and `device-root-ca.pem` is unsupported. Those are server managed certificates independent of this process because their certificate structure is completely different than those used as signer CA certificates for devices. And also since they are produced by the NH setup, they are not needed for verification
