### ISSUE TITLE
Multiple JITP CA per product

### ISSUE THREAD

**Issue by jeanparpaillon** [nerves-hub/nerves_hub_web#871]
Hi all,
If I understand correctly (https://github.com/nerves-hub/nerves_hub_web/blob/main/apps/nerves_hub_web_core/priv/repo/migrations/20210511162245_add_jitp_to_ca_certificates.exs#L12 ), only one CA per product can be JITP-enabled. 

I would like to be able to have multiple CA per product, with JITP enabled.

**Comment by fhunleth** [comment]
The relation is the other way. @jjcarstens can comment on that line. However, it should be many CAs to one product.

A CA can only JITP for one product, though. You can't have one CA JITP'ing for multiple products since NH wouldn't know which product to assign to the device when it first authenticates.

**Comment by jeanparpaillon** [comment]
I understand a CA can only JITP for one product.
I may be wrong, but on line 12,  `create unique_index(:jitp, [:product_id])` enforces a single JITP enabled CA per product.
From https://github.com/nerves-hub/nerves_hub_web/blob/main/apps/nerves_hub_web_core/lib/nerves_hub_web_core/products/product.ex#L22 , we have in `Product` : `has_one :jitp`

@jjcarstens can you explain this limitation ?

**Comment by fhunleth** [comment]
Got it. I forgot the discussion and just assumed that it was working for us internally at one time. The restriction doesn't make sense, and if it's as simple as removing the linked index for `:product_id`, then I'm definitely for it.
